// vim:set ro: -*- buffer-read-only:t -*-
// This file was generated from CompilerDefinitions.tt. Please edit that file.
/* Original code Copyright (c) 2018 Shane Celis[1]

   Original code posted here[2].

   This comment generated by code-cite[3].

   [1]: https://twitter.com/shanecelis
   [2]: https://github.com/shanecelis/unity-compiler-definitions
   [3]: https://github.com/shanecelis/code-cite
*/
using UnityEngine;
using System.Collections;

public class CompilerDefinitions : MonoBehaviour {
  void Start() {
#if UNITY_EDITOR
    Defined("UNITY_EDITOR");
#endif
#if UNITY_EDITOR_WIN
    Defined("UNITY_EDITOR_WIN");
#endif
#if UNITY_EDITOR_OSX
    Defined("UNITY_EDITOR_OSX");
#endif
#if UNITY_STANDALONE_OSX
    Defined("UNITY_STANDALONE_OSX");
#endif
#if UNITY_STANDALONE_WIN
    Defined("UNITY_STANDALONE_WIN");
#endif
#if UNITY_STANDALONE_LINUX
    Defined("UNITY_STANDALONE_LINUX");
#endif
#if UNITY_STANDALONE
    Defined("UNITY_STANDALONE");
#endif
#if UNITY_WII
    Defined("UNITY_WII");
#endif
#if UNITY_IOS
    Defined("UNITY_IOS");
#endif
#if UNITY_IPHONE
    Defined("UNITY_IPHONE");
#endif
#if UNITY_ANDROID
    Defined("UNITY_ANDROID");
#endif
#if UNITY_PS4
    Defined("UNITY_PS4");
#endif
#if UNITY_XBOXONE
    Defined("UNITY_XBOXONE");
#endif
#if UNITY_TIZEN
    Defined("UNITY_TIZEN");
#endif
#if UNITY_TVOS
    Defined("UNITY_TVOS");
#endif
#if UNITY_WSA
    Defined("UNITY_WSA");
#endif
#if UNITY_WSA_10_0
    Defined("UNITY_WSA_10_0");
#endif
#if UNITY_WINRT
    Defined("UNITY_WINRT");
#endif
#if UNITY_WEBGL
    Defined("UNITY_WEBGL");
#endif
#if UNITY_FACEBOOK
    Defined("UNITY_FACEBOOK");
#endif
#if UNITY_ADS
    Defined("UNITY_ADS");
#endif
#if UNITY_ANALYTICS
    Defined("UNITY_ANALYTICS");
#endif
#if UNITY_ASSERTIONS
    Defined("UNITY_ASSERTIONS");
#endif
#if ENABLE_MONO
    Defined("ENABLE_MONO");
#endif
#if ENABLE_IL2CPP
    Defined("ENABLE_IL2CPP");
#endif
#if ENABLE_DOTNET
    Defined("ENABLE_DOTNET");
#endif
#if NET_2_0
    Defined("NET_2_0");
#endif
#if NET_2_0_SUBSET
    Defined("NET_2_0_SUBSET");
#endif
#if NET_4_6
    Defined("NET_4_6");
#endif
#if NET_STANDARD_2_0
    Defined("NET_STANDARD_2_0");
#endif
#if ENABLE_WINMD_SUPPORT
    Defined("ENABLE_WINMD_SUPPORT");
#endif
#if UNITY_4
    Defined("UNITY_4");
#endif
#if UNITY_4_0
    Defined("UNITY_4_0");
#endif
#if UNITY_4_0_0
    Defined("UNITY_4_0_0");
#endif
#if UNITY_4_0_1
    Defined("UNITY_4_0_1");
#endif
#if UNITY_4_0_2
    Defined("UNITY_4_0_2");
#endif
#if UNITY_4_0_3
    Defined("UNITY_4_0_3");
#endif
#if UNITY_4_0_4
    Defined("UNITY_4_0_4");
#endif
#if UNITY_4_0_5
    Defined("UNITY_4_0_5");
#endif
#if UNITY_4_0_6
    Defined("UNITY_4_0_6");
#endif
#if UNITY_4_0_7
    Defined("UNITY_4_0_7");
#endif
#if UNITY_4_0_8
    Defined("UNITY_4_0_8");
#endif
#if UNITY_4_0_9
    Defined("UNITY_4_0_9");
#endif
#if UNITY_4_0_10
    Defined("UNITY_4_0_10");
#endif
#if UNITY_4_0_11
    Defined("UNITY_4_0_11");
#endif
#if UNITY_4_1
    Defined("UNITY_4_1");
#endif
#if UNITY_4_1_0
    Defined("UNITY_4_1_0");
#endif
#if UNITY_4_1_1
    Defined("UNITY_4_1_1");
#endif
#if UNITY_4_1_2
    Defined("UNITY_4_1_2");
#endif
#if UNITY_4_1_3
    Defined("UNITY_4_1_3");
#endif
#if UNITY_4_1_4
    Defined("UNITY_4_1_4");
#endif
#if UNITY_4_1_5
    Defined("UNITY_4_1_5");
#endif
#if UNITY_4_1_6
    Defined("UNITY_4_1_6");
#endif
#if UNITY_4_1_7
    Defined("UNITY_4_1_7");
#endif
#if UNITY_4_1_8
    Defined("UNITY_4_1_8");
#endif
#if UNITY_4_1_9
    Defined("UNITY_4_1_9");
#endif
#if UNITY_4_1_10
    Defined("UNITY_4_1_10");
#endif
#if UNITY_4_1_11
    Defined("UNITY_4_1_11");
#endif
#if UNITY_4_2
    Defined("UNITY_4_2");
#endif
#if UNITY_4_2_0
    Defined("UNITY_4_2_0");
#endif
#if UNITY_4_2_1
    Defined("UNITY_4_2_1");
#endif
#if UNITY_4_2_2
    Defined("UNITY_4_2_2");
#endif
#if UNITY_4_2_3
    Defined("UNITY_4_2_3");
#endif
#if UNITY_4_2_4
    Defined("UNITY_4_2_4");
#endif
#if UNITY_4_2_5
    Defined("UNITY_4_2_5");
#endif
#if UNITY_4_2_6
    Defined("UNITY_4_2_6");
#endif
#if UNITY_4_2_7
    Defined("UNITY_4_2_7");
#endif
#if UNITY_4_2_8
    Defined("UNITY_4_2_8");
#endif
#if UNITY_4_2_9
    Defined("UNITY_4_2_9");
#endif
#if UNITY_4_2_10
    Defined("UNITY_4_2_10");
#endif
#if UNITY_4_2_11
    Defined("UNITY_4_2_11");
#endif
#if UNITY_4_3
    Defined("UNITY_4_3");
#endif
#if UNITY_4_3_0
    Defined("UNITY_4_3_0");
#endif
#if UNITY_4_3_1
    Defined("UNITY_4_3_1");
#endif
#if UNITY_4_3_2
    Defined("UNITY_4_3_2");
#endif
#if UNITY_4_3_3
    Defined("UNITY_4_3_3");
#endif
#if UNITY_4_3_4
    Defined("UNITY_4_3_4");
#endif
#if UNITY_4_3_5
    Defined("UNITY_4_3_5");
#endif
#if UNITY_4_3_6
    Defined("UNITY_4_3_6");
#endif
#if UNITY_4_3_7
    Defined("UNITY_4_3_7");
#endif
#if UNITY_4_3_8
    Defined("UNITY_4_3_8");
#endif
#if UNITY_4_3_9
    Defined("UNITY_4_3_9");
#endif
#if UNITY_4_3_10
    Defined("UNITY_4_3_10");
#endif
#if UNITY_4_3_11
    Defined("UNITY_4_3_11");
#endif
#if UNITY_4_4
    Defined("UNITY_4_4");
#endif
#if UNITY_4_4_0
    Defined("UNITY_4_4_0");
#endif
#if UNITY_4_4_1
    Defined("UNITY_4_4_1");
#endif
#if UNITY_4_4_2
    Defined("UNITY_4_4_2");
#endif
#if UNITY_4_4_3
    Defined("UNITY_4_4_3");
#endif
#if UNITY_4_4_4
    Defined("UNITY_4_4_4");
#endif
#if UNITY_4_4_5
    Defined("UNITY_4_4_5");
#endif
#if UNITY_4_4_6
    Defined("UNITY_4_4_6");
#endif
#if UNITY_4_4_7
    Defined("UNITY_4_4_7");
#endif
#if UNITY_4_4_8
    Defined("UNITY_4_4_8");
#endif
#if UNITY_4_4_9
    Defined("UNITY_4_4_9");
#endif
#if UNITY_4_4_10
    Defined("UNITY_4_4_10");
#endif
#if UNITY_4_4_11
    Defined("UNITY_4_4_11");
#endif
#if UNITY_4_5
    Defined("UNITY_4_5");
#endif
#if UNITY_4_5_0
    Defined("UNITY_4_5_0");
#endif
#if UNITY_4_5_1
    Defined("UNITY_4_5_1");
#endif
#if UNITY_4_5_2
    Defined("UNITY_4_5_2");
#endif
#if UNITY_4_5_3
    Defined("UNITY_4_5_3");
#endif
#if UNITY_4_5_4
    Defined("UNITY_4_5_4");
#endif
#if UNITY_4_5_5
    Defined("UNITY_4_5_5");
#endif
#if UNITY_4_5_6
    Defined("UNITY_4_5_6");
#endif
#if UNITY_4_5_7
    Defined("UNITY_4_5_7");
#endif
#if UNITY_4_5_8
    Defined("UNITY_4_5_8");
#endif
#if UNITY_4_5_9
    Defined("UNITY_4_5_9");
#endif
#if UNITY_4_5_10
    Defined("UNITY_4_5_10");
#endif
#if UNITY_4_5_11
    Defined("UNITY_4_5_11");
#endif
#if UNITY_4_6
    Defined("UNITY_4_6");
#endif
#if UNITY_4_6_0
    Defined("UNITY_4_6_0");
#endif
#if UNITY_4_6_1
    Defined("UNITY_4_6_1");
#endif
#if UNITY_4_6_2
    Defined("UNITY_4_6_2");
#endif
#if UNITY_4_6_3
    Defined("UNITY_4_6_3");
#endif
#if UNITY_4_6_4
    Defined("UNITY_4_6_4");
#endif
#if UNITY_4_6_5
    Defined("UNITY_4_6_5");
#endif
#if UNITY_4_6_6
    Defined("UNITY_4_6_6");
#endif
#if UNITY_4_6_7
    Defined("UNITY_4_6_7");
#endif
#if UNITY_4_6_8
    Defined("UNITY_4_6_8");
#endif
#if UNITY_4_6_9
    Defined("UNITY_4_6_9");
#endif
#if UNITY_4_6_10
    Defined("UNITY_4_6_10");
#endif
#if UNITY_4_6_11
    Defined("UNITY_4_6_11");
#endif
#if UNITY_4_7
    Defined("UNITY_4_7");
#endif
#if UNITY_4_7_0
    Defined("UNITY_4_7_0");
#endif
#if UNITY_4_7_1
    Defined("UNITY_4_7_1");
#endif
#if UNITY_4_7_2
    Defined("UNITY_4_7_2");
#endif
#if UNITY_4_7_3
    Defined("UNITY_4_7_3");
#endif
#if UNITY_4_7_4
    Defined("UNITY_4_7_4");
#endif
#if UNITY_4_7_5
    Defined("UNITY_4_7_5");
#endif
#if UNITY_4_7_6
    Defined("UNITY_4_7_6");
#endif
#if UNITY_4_7_7
    Defined("UNITY_4_7_7");
#endif
#if UNITY_4_7_8
    Defined("UNITY_4_7_8");
#endif
#if UNITY_4_7_9
    Defined("UNITY_4_7_9");
#endif
#if UNITY_4_7_10
    Defined("UNITY_4_7_10");
#endif
#if UNITY_4_7_11
    Defined("UNITY_4_7_11");
#endif
#if UNITY_4_8
    Defined("UNITY_4_8");
#endif
#if UNITY_4_8_0
    Defined("UNITY_4_8_0");
#endif
#if UNITY_4_8_1
    Defined("UNITY_4_8_1");
#endif
#if UNITY_4_8_2
    Defined("UNITY_4_8_2");
#endif
#if UNITY_4_8_3
    Defined("UNITY_4_8_3");
#endif
#if UNITY_4_8_4
    Defined("UNITY_4_8_4");
#endif
#if UNITY_4_8_5
    Defined("UNITY_4_8_5");
#endif
#if UNITY_4_8_6
    Defined("UNITY_4_8_6");
#endif
#if UNITY_4_8_7
    Defined("UNITY_4_8_7");
#endif
#if UNITY_4_8_8
    Defined("UNITY_4_8_8");
#endif
#if UNITY_4_8_9
    Defined("UNITY_4_8_9");
#endif
#if UNITY_4_8_10
    Defined("UNITY_4_8_10");
#endif
#if UNITY_4_8_11
    Defined("UNITY_4_8_11");
#endif
#if UNITY_4_9
    Defined("UNITY_4_9");
#endif
#if UNITY_4_9_0
    Defined("UNITY_4_9_0");
#endif
#if UNITY_4_9_1
    Defined("UNITY_4_9_1");
#endif
#if UNITY_4_9_2
    Defined("UNITY_4_9_2");
#endif
#if UNITY_4_9_3
    Defined("UNITY_4_9_3");
#endif
#if UNITY_4_9_4
    Defined("UNITY_4_9_4");
#endif
#if UNITY_4_9_5
    Defined("UNITY_4_9_5");
#endif
#if UNITY_4_9_6
    Defined("UNITY_4_9_6");
#endif
#if UNITY_4_9_7
    Defined("UNITY_4_9_7");
#endif
#if UNITY_4_9_8
    Defined("UNITY_4_9_8");
#endif
#if UNITY_4_9_9
    Defined("UNITY_4_9_9");
#endif
#if UNITY_4_9_10
    Defined("UNITY_4_9_10");
#endif
#if UNITY_4_9_11
    Defined("UNITY_4_9_11");
#endif
#if UNITY_4_10
    Defined("UNITY_4_10");
#endif
#if UNITY_4_10_0
    Defined("UNITY_4_10_0");
#endif
#if UNITY_4_10_1
    Defined("UNITY_4_10_1");
#endif
#if UNITY_4_10_2
    Defined("UNITY_4_10_2");
#endif
#if UNITY_4_10_3
    Defined("UNITY_4_10_3");
#endif
#if UNITY_4_10_4
    Defined("UNITY_4_10_4");
#endif
#if UNITY_4_10_5
    Defined("UNITY_4_10_5");
#endif
#if UNITY_4_10_6
    Defined("UNITY_4_10_6");
#endif
#if UNITY_4_10_7
    Defined("UNITY_4_10_7");
#endif
#if UNITY_4_10_8
    Defined("UNITY_4_10_8");
#endif
#if UNITY_4_10_9
    Defined("UNITY_4_10_9");
#endif
#if UNITY_4_10_10
    Defined("UNITY_4_10_10");
#endif
#if UNITY_4_10_11
    Defined("UNITY_4_10_11");
#endif
#if UNITY_4_11
    Defined("UNITY_4_11");
#endif
#if UNITY_4_11_0
    Defined("UNITY_4_11_0");
#endif
#if UNITY_4_11_1
    Defined("UNITY_4_11_1");
#endif
#if UNITY_4_11_2
    Defined("UNITY_4_11_2");
#endif
#if UNITY_4_11_3
    Defined("UNITY_4_11_3");
#endif
#if UNITY_4_11_4
    Defined("UNITY_4_11_4");
#endif
#if UNITY_4_11_5
    Defined("UNITY_4_11_5");
#endif
#if UNITY_4_11_6
    Defined("UNITY_4_11_6");
#endif
#if UNITY_4_11_7
    Defined("UNITY_4_11_7");
#endif
#if UNITY_4_11_8
    Defined("UNITY_4_11_8");
#endif
#if UNITY_4_11_9
    Defined("UNITY_4_11_9");
#endif
#if UNITY_4_11_10
    Defined("UNITY_4_11_10");
#endif
#if UNITY_4_11_11
    Defined("UNITY_4_11_11");
#endif
#if UNITY_5
    Defined("UNITY_5");
#endif
#if UNITY_5_0
    Defined("UNITY_5_0");
#endif
#if UNITY_5_0_0
    Defined("UNITY_5_0_0");
#endif
#if UNITY_5_0_1
    Defined("UNITY_5_0_1");
#endif
#if UNITY_5_0_2
    Defined("UNITY_5_0_2");
#endif
#if UNITY_5_0_3
    Defined("UNITY_5_0_3");
#endif
#if UNITY_5_0_4
    Defined("UNITY_5_0_4");
#endif
#if UNITY_5_0_5
    Defined("UNITY_5_0_5");
#endif
#if UNITY_5_0_6
    Defined("UNITY_5_0_6");
#endif
#if UNITY_5_0_7
    Defined("UNITY_5_0_7");
#endif
#if UNITY_5_0_8
    Defined("UNITY_5_0_8");
#endif
#if UNITY_5_0_9
    Defined("UNITY_5_0_9");
#endif
#if UNITY_5_0_10
    Defined("UNITY_5_0_10");
#endif
#if UNITY_5_0_11
    Defined("UNITY_5_0_11");
#endif
#if UNITY_5_1
    Defined("UNITY_5_1");
#endif
#if UNITY_5_1_0
    Defined("UNITY_5_1_0");
#endif
#if UNITY_5_1_1
    Defined("UNITY_5_1_1");
#endif
#if UNITY_5_1_2
    Defined("UNITY_5_1_2");
#endif
#if UNITY_5_1_3
    Defined("UNITY_5_1_3");
#endif
#if UNITY_5_1_4
    Defined("UNITY_5_1_4");
#endif
#if UNITY_5_1_5
    Defined("UNITY_5_1_5");
#endif
#if UNITY_5_1_6
    Defined("UNITY_5_1_6");
#endif
#if UNITY_5_1_7
    Defined("UNITY_5_1_7");
#endif
#if UNITY_5_1_8
    Defined("UNITY_5_1_8");
#endif
#if UNITY_5_1_9
    Defined("UNITY_5_1_9");
#endif
#if UNITY_5_1_10
    Defined("UNITY_5_1_10");
#endif
#if UNITY_5_1_11
    Defined("UNITY_5_1_11");
#endif
#if UNITY_5_2
    Defined("UNITY_5_2");
#endif
#if UNITY_5_2_0
    Defined("UNITY_5_2_0");
#endif
#if UNITY_5_2_1
    Defined("UNITY_5_2_1");
#endif
#if UNITY_5_2_2
    Defined("UNITY_5_2_2");
#endif
#if UNITY_5_2_3
    Defined("UNITY_5_2_3");
#endif
#if UNITY_5_2_4
    Defined("UNITY_5_2_4");
#endif
#if UNITY_5_2_5
    Defined("UNITY_5_2_5");
#endif
#if UNITY_5_2_6
    Defined("UNITY_5_2_6");
#endif
#if UNITY_5_2_7
    Defined("UNITY_5_2_7");
#endif
#if UNITY_5_2_8
    Defined("UNITY_5_2_8");
#endif
#if UNITY_5_2_9
    Defined("UNITY_5_2_9");
#endif
#if UNITY_5_2_10
    Defined("UNITY_5_2_10");
#endif
#if UNITY_5_2_11
    Defined("UNITY_5_2_11");
#endif
#if UNITY_5_3
    Defined("UNITY_5_3");
#endif
#if UNITY_5_3_0
    Defined("UNITY_5_3_0");
#endif
#if UNITY_5_3_1
    Defined("UNITY_5_3_1");
#endif
#if UNITY_5_3_2
    Defined("UNITY_5_3_2");
#endif
#if UNITY_5_3_3
    Defined("UNITY_5_3_3");
#endif
#if UNITY_5_3_4
    Defined("UNITY_5_3_4");
#endif
#if UNITY_5_3_5
    Defined("UNITY_5_3_5");
#endif
#if UNITY_5_3_6
    Defined("UNITY_5_3_6");
#endif
#if UNITY_5_3_7
    Defined("UNITY_5_3_7");
#endif
#if UNITY_5_3_8
    Defined("UNITY_5_3_8");
#endif
#if UNITY_5_3_9
    Defined("UNITY_5_3_9");
#endif
#if UNITY_5_3_10
    Defined("UNITY_5_3_10");
#endif
#if UNITY_5_3_11
    Defined("UNITY_5_3_11");
#endif
#if UNITY_5_4
    Defined("UNITY_5_4");
#endif
#if UNITY_5_4_0
    Defined("UNITY_5_4_0");
#endif
#if UNITY_5_4_1
    Defined("UNITY_5_4_1");
#endif
#if UNITY_5_4_2
    Defined("UNITY_5_4_2");
#endif
#if UNITY_5_4_3
    Defined("UNITY_5_4_3");
#endif
#if UNITY_5_4_4
    Defined("UNITY_5_4_4");
#endif
#if UNITY_5_4_5
    Defined("UNITY_5_4_5");
#endif
#if UNITY_5_4_6
    Defined("UNITY_5_4_6");
#endif
#if UNITY_5_4_7
    Defined("UNITY_5_4_7");
#endif
#if UNITY_5_4_8
    Defined("UNITY_5_4_8");
#endif
#if UNITY_5_4_9
    Defined("UNITY_5_4_9");
#endif
#if UNITY_5_4_10
    Defined("UNITY_5_4_10");
#endif
#if UNITY_5_4_11
    Defined("UNITY_5_4_11");
#endif
#if UNITY_5_5
    Defined("UNITY_5_5");
#endif
#if UNITY_5_5_0
    Defined("UNITY_5_5_0");
#endif
#if UNITY_5_5_1
    Defined("UNITY_5_5_1");
#endif
#if UNITY_5_5_2
    Defined("UNITY_5_5_2");
#endif
#if UNITY_5_5_3
    Defined("UNITY_5_5_3");
#endif
#if UNITY_5_5_4
    Defined("UNITY_5_5_4");
#endif
#if UNITY_5_5_5
    Defined("UNITY_5_5_5");
#endif
#if UNITY_5_5_6
    Defined("UNITY_5_5_6");
#endif
#if UNITY_5_5_7
    Defined("UNITY_5_5_7");
#endif
#if UNITY_5_5_8
    Defined("UNITY_5_5_8");
#endif
#if UNITY_5_5_9
    Defined("UNITY_5_5_9");
#endif
#if UNITY_5_5_10
    Defined("UNITY_5_5_10");
#endif
#if UNITY_5_5_11
    Defined("UNITY_5_5_11");
#endif
#if UNITY_5_6
    Defined("UNITY_5_6");
#endif
#if UNITY_5_6_0
    Defined("UNITY_5_6_0");
#endif
#if UNITY_5_6_1
    Defined("UNITY_5_6_1");
#endif
#if UNITY_5_6_2
    Defined("UNITY_5_6_2");
#endif
#if UNITY_5_6_3
    Defined("UNITY_5_6_3");
#endif
#if UNITY_5_6_4
    Defined("UNITY_5_6_4");
#endif
#if UNITY_5_6_5
    Defined("UNITY_5_6_5");
#endif
#if UNITY_5_6_6
    Defined("UNITY_5_6_6");
#endif
#if UNITY_5_6_7
    Defined("UNITY_5_6_7");
#endif
#if UNITY_5_6_8
    Defined("UNITY_5_6_8");
#endif
#if UNITY_5_6_9
    Defined("UNITY_5_6_9");
#endif
#if UNITY_5_6_10
    Defined("UNITY_5_6_10");
#endif
#if UNITY_5_6_11
    Defined("UNITY_5_6_11");
#endif
#if UNITY_5_7
    Defined("UNITY_5_7");
#endif
#if UNITY_5_7_0
    Defined("UNITY_5_7_0");
#endif
#if UNITY_5_7_1
    Defined("UNITY_5_7_1");
#endif
#if UNITY_5_7_2
    Defined("UNITY_5_7_2");
#endif
#if UNITY_5_7_3
    Defined("UNITY_5_7_3");
#endif
#if UNITY_5_7_4
    Defined("UNITY_5_7_4");
#endif
#if UNITY_5_7_5
    Defined("UNITY_5_7_5");
#endif
#if UNITY_5_7_6
    Defined("UNITY_5_7_6");
#endif
#if UNITY_5_7_7
    Defined("UNITY_5_7_7");
#endif
#if UNITY_5_7_8
    Defined("UNITY_5_7_8");
#endif
#if UNITY_5_7_9
    Defined("UNITY_5_7_9");
#endif
#if UNITY_5_7_10
    Defined("UNITY_5_7_10");
#endif
#if UNITY_5_7_11
    Defined("UNITY_5_7_11");
#endif
#if UNITY_5_8
    Defined("UNITY_5_8");
#endif
#if UNITY_5_8_0
    Defined("UNITY_5_8_0");
#endif
#if UNITY_5_8_1
    Defined("UNITY_5_8_1");
#endif
#if UNITY_5_8_2
    Defined("UNITY_5_8_2");
#endif
#if UNITY_5_8_3
    Defined("UNITY_5_8_3");
#endif
#if UNITY_5_8_4
    Defined("UNITY_5_8_4");
#endif
#if UNITY_5_8_5
    Defined("UNITY_5_8_5");
#endif
#if UNITY_5_8_6
    Defined("UNITY_5_8_6");
#endif
#if UNITY_5_8_7
    Defined("UNITY_5_8_7");
#endif
#if UNITY_5_8_8
    Defined("UNITY_5_8_8");
#endif
#if UNITY_5_8_9
    Defined("UNITY_5_8_9");
#endif
#if UNITY_5_8_10
    Defined("UNITY_5_8_10");
#endif
#if UNITY_5_8_11
    Defined("UNITY_5_8_11");
#endif
#if UNITY_5_9
    Defined("UNITY_5_9");
#endif
#if UNITY_5_9_0
    Defined("UNITY_5_9_0");
#endif
#if UNITY_5_9_1
    Defined("UNITY_5_9_1");
#endif
#if UNITY_5_9_2
    Defined("UNITY_5_9_2");
#endif
#if UNITY_5_9_3
    Defined("UNITY_5_9_3");
#endif
#if UNITY_5_9_4
    Defined("UNITY_5_9_4");
#endif
#if UNITY_5_9_5
    Defined("UNITY_5_9_5");
#endif
#if UNITY_5_9_6
    Defined("UNITY_5_9_6");
#endif
#if UNITY_5_9_7
    Defined("UNITY_5_9_7");
#endif
#if UNITY_5_9_8
    Defined("UNITY_5_9_8");
#endif
#if UNITY_5_9_9
    Defined("UNITY_5_9_9");
#endif
#if UNITY_5_9_10
    Defined("UNITY_5_9_10");
#endif
#if UNITY_5_9_11
    Defined("UNITY_5_9_11");
#endif
#if UNITY_5_10
    Defined("UNITY_5_10");
#endif
#if UNITY_5_10_0
    Defined("UNITY_5_10_0");
#endif
#if UNITY_5_10_1
    Defined("UNITY_5_10_1");
#endif
#if UNITY_5_10_2
    Defined("UNITY_5_10_2");
#endif
#if UNITY_5_10_3
    Defined("UNITY_5_10_3");
#endif
#if UNITY_5_10_4
    Defined("UNITY_5_10_4");
#endif
#if UNITY_5_10_5
    Defined("UNITY_5_10_5");
#endif
#if UNITY_5_10_6
    Defined("UNITY_5_10_6");
#endif
#if UNITY_5_10_7
    Defined("UNITY_5_10_7");
#endif
#if UNITY_5_10_8
    Defined("UNITY_5_10_8");
#endif
#if UNITY_5_10_9
    Defined("UNITY_5_10_9");
#endif
#if UNITY_5_10_10
    Defined("UNITY_5_10_10");
#endif
#if UNITY_5_10_11
    Defined("UNITY_5_10_11");
#endif
#if UNITY_5_11
    Defined("UNITY_5_11");
#endif
#if UNITY_5_11_0
    Defined("UNITY_5_11_0");
#endif
#if UNITY_5_11_1
    Defined("UNITY_5_11_1");
#endif
#if UNITY_5_11_2
    Defined("UNITY_5_11_2");
#endif
#if UNITY_5_11_3
    Defined("UNITY_5_11_3");
#endif
#if UNITY_5_11_4
    Defined("UNITY_5_11_4");
#endif
#if UNITY_5_11_5
    Defined("UNITY_5_11_5");
#endif
#if UNITY_5_11_6
    Defined("UNITY_5_11_6");
#endif
#if UNITY_5_11_7
    Defined("UNITY_5_11_7");
#endif
#if UNITY_5_11_8
    Defined("UNITY_5_11_8");
#endif
#if UNITY_5_11_9
    Defined("UNITY_5_11_9");
#endif
#if UNITY_5_11_10
    Defined("UNITY_5_11_10");
#endif
#if UNITY_5_11_11
    Defined("UNITY_5_11_11");
#endif
#if UNITY_2017
    Defined("UNITY_2017");
#endif
#if UNITY_2017_0
    Defined("UNITY_2017_0");
#endif
#if UNITY_2017_0_0
    Defined("UNITY_2017_0_0");
#endif
#if UNITY_2017_0_1
    Defined("UNITY_2017_0_1");
#endif
#if UNITY_2017_0_2
    Defined("UNITY_2017_0_2");
#endif
#if UNITY_2017_0_3
    Defined("UNITY_2017_0_3");
#endif
#if UNITY_2017_0_4
    Defined("UNITY_2017_0_4");
#endif
#if UNITY_2017_0_5
    Defined("UNITY_2017_0_5");
#endif
#if UNITY_2017_0_6
    Defined("UNITY_2017_0_6");
#endif
#if UNITY_2017_0_7
    Defined("UNITY_2017_0_7");
#endif
#if UNITY_2017_0_8
    Defined("UNITY_2017_0_8");
#endif
#if UNITY_2017_0_9
    Defined("UNITY_2017_0_9");
#endif
#if UNITY_2017_0_10
    Defined("UNITY_2017_0_10");
#endif
#if UNITY_2017_0_11
    Defined("UNITY_2017_0_11");
#endif
#if UNITY_2017_1
    Defined("UNITY_2017_1");
#endif
#if UNITY_2017_1_0
    Defined("UNITY_2017_1_0");
#endif
#if UNITY_2017_1_1
    Defined("UNITY_2017_1_1");
#endif
#if UNITY_2017_1_2
    Defined("UNITY_2017_1_2");
#endif
#if UNITY_2017_1_3
    Defined("UNITY_2017_1_3");
#endif
#if UNITY_2017_1_4
    Defined("UNITY_2017_1_4");
#endif
#if UNITY_2017_1_5
    Defined("UNITY_2017_1_5");
#endif
#if UNITY_2017_1_6
    Defined("UNITY_2017_1_6");
#endif
#if UNITY_2017_1_7
    Defined("UNITY_2017_1_7");
#endif
#if UNITY_2017_1_8
    Defined("UNITY_2017_1_8");
#endif
#if UNITY_2017_1_9
    Defined("UNITY_2017_1_9");
#endif
#if UNITY_2017_1_10
    Defined("UNITY_2017_1_10");
#endif
#if UNITY_2017_1_11
    Defined("UNITY_2017_1_11");
#endif
#if UNITY_2017_2
    Defined("UNITY_2017_2");
#endif
#if UNITY_2017_2_0
    Defined("UNITY_2017_2_0");
#endif
#if UNITY_2017_2_1
    Defined("UNITY_2017_2_1");
#endif
#if UNITY_2017_2_2
    Defined("UNITY_2017_2_2");
#endif
#if UNITY_2017_2_3
    Defined("UNITY_2017_2_3");
#endif
#if UNITY_2017_2_4
    Defined("UNITY_2017_2_4");
#endif
#if UNITY_2017_2_5
    Defined("UNITY_2017_2_5");
#endif
#if UNITY_2017_2_6
    Defined("UNITY_2017_2_6");
#endif
#if UNITY_2017_2_7
    Defined("UNITY_2017_2_7");
#endif
#if UNITY_2017_2_8
    Defined("UNITY_2017_2_8");
#endif
#if UNITY_2017_2_9
    Defined("UNITY_2017_2_9");
#endif
#if UNITY_2017_2_10
    Defined("UNITY_2017_2_10");
#endif
#if UNITY_2017_2_11
    Defined("UNITY_2017_2_11");
#endif
#if UNITY_2017_3
    Defined("UNITY_2017_3");
#endif
#if UNITY_2017_3_0
    Defined("UNITY_2017_3_0");
#endif
#if UNITY_2017_3_1
    Defined("UNITY_2017_3_1");
#endif
#if UNITY_2017_3_2
    Defined("UNITY_2017_3_2");
#endif
#if UNITY_2017_3_3
    Defined("UNITY_2017_3_3");
#endif
#if UNITY_2017_3_4
    Defined("UNITY_2017_3_4");
#endif
#if UNITY_2017_3_5
    Defined("UNITY_2017_3_5");
#endif
#if UNITY_2017_3_6
    Defined("UNITY_2017_3_6");
#endif
#if UNITY_2017_3_7
    Defined("UNITY_2017_3_7");
#endif
#if UNITY_2017_3_8
    Defined("UNITY_2017_3_8");
#endif
#if UNITY_2017_3_9
    Defined("UNITY_2017_3_9");
#endif
#if UNITY_2017_3_10
    Defined("UNITY_2017_3_10");
#endif
#if UNITY_2017_3_11
    Defined("UNITY_2017_3_11");
#endif
#if UNITY_2017_4
    Defined("UNITY_2017_4");
#endif
#if UNITY_2017_4_0
    Defined("UNITY_2017_4_0");
#endif
#if UNITY_2017_4_1
    Defined("UNITY_2017_4_1");
#endif
#if UNITY_2017_4_2
    Defined("UNITY_2017_4_2");
#endif
#if UNITY_2017_4_3
    Defined("UNITY_2017_4_3");
#endif
#if UNITY_2017_4_4
    Defined("UNITY_2017_4_4");
#endif
#if UNITY_2017_4_5
    Defined("UNITY_2017_4_5");
#endif
#if UNITY_2017_4_6
    Defined("UNITY_2017_4_6");
#endif
#if UNITY_2017_4_7
    Defined("UNITY_2017_4_7");
#endif
#if UNITY_2017_4_8
    Defined("UNITY_2017_4_8");
#endif
#if UNITY_2017_4_9
    Defined("UNITY_2017_4_9");
#endif
#if UNITY_2017_4_10
    Defined("UNITY_2017_4_10");
#endif
#if UNITY_2017_4_11
    Defined("UNITY_2017_4_11");
#endif
#if UNITY_2017_5
    Defined("UNITY_2017_5");
#endif
#if UNITY_2017_5_0
    Defined("UNITY_2017_5_0");
#endif
#if UNITY_2017_5_1
    Defined("UNITY_2017_5_1");
#endif
#if UNITY_2017_5_2
    Defined("UNITY_2017_5_2");
#endif
#if UNITY_2017_5_3
    Defined("UNITY_2017_5_3");
#endif
#if UNITY_2017_5_4
    Defined("UNITY_2017_5_4");
#endif
#if UNITY_2017_5_5
    Defined("UNITY_2017_5_5");
#endif
#if UNITY_2017_5_6
    Defined("UNITY_2017_5_6");
#endif
#if UNITY_2017_5_7
    Defined("UNITY_2017_5_7");
#endif
#if UNITY_2017_5_8
    Defined("UNITY_2017_5_8");
#endif
#if UNITY_2017_5_9
    Defined("UNITY_2017_5_9");
#endif
#if UNITY_2017_5_10
    Defined("UNITY_2017_5_10");
#endif
#if UNITY_2017_5_11
    Defined("UNITY_2017_5_11");
#endif
#if UNITY_2017_6
    Defined("UNITY_2017_6");
#endif
#if UNITY_2017_6_0
    Defined("UNITY_2017_6_0");
#endif
#if UNITY_2017_6_1
    Defined("UNITY_2017_6_1");
#endif
#if UNITY_2017_6_2
    Defined("UNITY_2017_6_2");
#endif
#if UNITY_2017_6_3
    Defined("UNITY_2017_6_3");
#endif
#if UNITY_2017_6_4
    Defined("UNITY_2017_6_4");
#endif
#if UNITY_2017_6_5
    Defined("UNITY_2017_6_5");
#endif
#if UNITY_2017_6_6
    Defined("UNITY_2017_6_6");
#endif
#if UNITY_2017_6_7
    Defined("UNITY_2017_6_7");
#endif
#if UNITY_2017_6_8
    Defined("UNITY_2017_6_8");
#endif
#if UNITY_2017_6_9
    Defined("UNITY_2017_6_9");
#endif
#if UNITY_2017_6_10
    Defined("UNITY_2017_6_10");
#endif
#if UNITY_2017_6_11
    Defined("UNITY_2017_6_11");
#endif
#if UNITY_2017_7
    Defined("UNITY_2017_7");
#endif
#if UNITY_2017_7_0
    Defined("UNITY_2017_7_0");
#endif
#if UNITY_2017_7_1
    Defined("UNITY_2017_7_1");
#endif
#if UNITY_2017_7_2
    Defined("UNITY_2017_7_2");
#endif
#if UNITY_2017_7_3
    Defined("UNITY_2017_7_3");
#endif
#if UNITY_2017_7_4
    Defined("UNITY_2017_7_4");
#endif
#if UNITY_2017_7_5
    Defined("UNITY_2017_7_5");
#endif
#if UNITY_2017_7_6
    Defined("UNITY_2017_7_6");
#endif
#if UNITY_2017_7_7
    Defined("UNITY_2017_7_7");
#endif
#if UNITY_2017_7_8
    Defined("UNITY_2017_7_8");
#endif
#if UNITY_2017_7_9
    Defined("UNITY_2017_7_9");
#endif
#if UNITY_2017_7_10
    Defined("UNITY_2017_7_10");
#endif
#if UNITY_2017_7_11
    Defined("UNITY_2017_7_11");
#endif
#if UNITY_2017_8
    Defined("UNITY_2017_8");
#endif
#if UNITY_2017_8_0
    Defined("UNITY_2017_8_0");
#endif
#if UNITY_2017_8_1
    Defined("UNITY_2017_8_1");
#endif
#if UNITY_2017_8_2
    Defined("UNITY_2017_8_2");
#endif
#if UNITY_2017_8_3
    Defined("UNITY_2017_8_3");
#endif
#if UNITY_2017_8_4
    Defined("UNITY_2017_8_4");
#endif
#if UNITY_2017_8_5
    Defined("UNITY_2017_8_5");
#endif
#if UNITY_2017_8_6
    Defined("UNITY_2017_8_6");
#endif
#if UNITY_2017_8_7
    Defined("UNITY_2017_8_7");
#endif
#if UNITY_2017_8_8
    Defined("UNITY_2017_8_8");
#endif
#if UNITY_2017_8_9
    Defined("UNITY_2017_8_9");
#endif
#if UNITY_2017_8_10
    Defined("UNITY_2017_8_10");
#endif
#if UNITY_2017_8_11
    Defined("UNITY_2017_8_11");
#endif
#if UNITY_2017_9
    Defined("UNITY_2017_9");
#endif
#if UNITY_2017_9_0
    Defined("UNITY_2017_9_0");
#endif
#if UNITY_2017_9_1
    Defined("UNITY_2017_9_1");
#endif
#if UNITY_2017_9_2
    Defined("UNITY_2017_9_2");
#endif
#if UNITY_2017_9_3
    Defined("UNITY_2017_9_3");
#endif
#if UNITY_2017_9_4
    Defined("UNITY_2017_9_4");
#endif
#if UNITY_2017_9_5
    Defined("UNITY_2017_9_5");
#endif
#if UNITY_2017_9_6
    Defined("UNITY_2017_9_6");
#endif
#if UNITY_2017_9_7
    Defined("UNITY_2017_9_7");
#endif
#if UNITY_2017_9_8
    Defined("UNITY_2017_9_8");
#endif
#if UNITY_2017_9_9
    Defined("UNITY_2017_9_9");
#endif
#if UNITY_2017_9_10
    Defined("UNITY_2017_9_10");
#endif
#if UNITY_2017_9_11
    Defined("UNITY_2017_9_11");
#endif
#if UNITY_2017_10
    Defined("UNITY_2017_10");
#endif
#if UNITY_2017_10_0
    Defined("UNITY_2017_10_0");
#endif
#if UNITY_2017_10_1
    Defined("UNITY_2017_10_1");
#endif
#if UNITY_2017_10_2
    Defined("UNITY_2017_10_2");
#endif
#if UNITY_2017_10_3
    Defined("UNITY_2017_10_3");
#endif
#if UNITY_2017_10_4
    Defined("UNITY_2017_10_4");
#endif
#if UNITY_2017_10_5
    Defined("UNITY_2017_10_5");
#endif
#if UNITY_2017_10_6
    Defined("UNITY_2017_10_6");
#endif
#if UNITY_2017_10_7
    Defined("UNITY_2017_10_7");
#endif
#if UNITY_2017_10_8
    Defined("UNITY_2017_10_8");
#endif
#if UNITY_2017_10_9
    Defined("UNITY_2017_10_9");
#endif
#if UNITY_2017_10_10
    Defined("UNITY_2017_10_10");
#endif
#if UNITY_2017_10_11
    Defined("UNITY_2017_10_11");
#endif
#if UNITY_2017_11
    Defined("UNITY_2017_11");
#endif
#if UNITY_2017_11_0
    Defined("UNITY_2017_11_0");
#endif
#if UNITY_2017_11_1
    Defined("UNITY_2017_11_1");
#endif
#if UNITY_2017_11_2
    Defined("UNITY_2017_11_2");
#endif
#if UNITY_2017_11_3
    Defined("UNITY_2017_11_3");
#endif
#if UNITY_2017_11_4
    Defined("UNITY_2017_11_4");
#endif
#if UNITY_2017_11_5
    Defined("UNITY_2017_11_5");
#endif
#if UNITY_2017_11_6
    Defined("UNITY_2017_11_6");
#endif
#if UNITY_2017_11_7
    Defined("UNITY_2017_11_7");
#endif
#if UNITY_2017_11_8
    Defined("UNITY_2017_11_8");
#endif
#if UNITY_2017_11_9
    Defined("UNITY_2017_11_9");
#endif
#if UNITY_2017_11_10
    Defined("UNITY_2017_11_10");
#endif
#if UNITY_2017_11_11
    Defined("UNITY_2017_11_11");
#endif
#if UNITY_2018
    Defined("UNITY_2018");
#endif
#if UNITY_2018_0
    Defined("UNITY_2018_0");
#endif
#if UNITY_2018_0_0
    Defined("UNITY_2018_0_0");
#endif
#if UNITY_2018_0_1
    Defined("UNITY_2018_0_1");
#endif
#if UNITY_2018_0_2
    Defined("UNITY_2018_0_2");
#endif
#if UNITY_2018_0_3
    Defined("UNITY_2018_0_3");
#endif
#if UNITY_2018_0_4
    Defined("UNITY_2018_0_4");
#endif
#if UNITY_2018_0_5
    Defined("UNITY_2018_0_5");
#endif
#if UNITY_2018_0_6
    Defined("UNITY_2018_0_6");
#endif
#if UNITY_2018_0_7
    Defined("UNITY_2018_0_7");
#endif
#if UNITY_2018_0_8
    Defined("UNITY_2018_0_8");
#endif
#if UNITY_2018_0_9
    Defined("UNITY_2018_0_9");
#endif
#if UNITY_2018_0_10
    Defined("UNITY_2018_0_10");
#endif
#if UNITY_2018_0_11
    Defined("UNITY_2018_0_11");
#endif
#if UNITY_2018_1
    Defined("UNITY_2018_1");
#endif
#if UNITY_2018_1_0
    Defined("UNITY_2018_1_0");
#endif
#if UNITY_2018_1_1
    Defined("UNITY_2018_1_1");
#endif
#if UNITY_2018_1_2
    Defined("UNITY_2018_1_2");
#endif
#if UNITY_2018_1_3
    Defined("UNITY_2018_1_3");
#endif
#if UNITY_2018_1_4
    Defined("UNITY_2018_1_4");
#endif
#if UNITY_2018_1_5
    Defined("UNITY_2018_1_5");
#endif
#if UNITY_2018_1_6
    Defined("UNITY_2018_1_6");
#endif
#if UNITY_2018_1_7
    Defined("UNITY_2018_1_7");
#endif
#if UNITY_2018_1_8
    Defined("UNITY_2018_1_8");
#endif
#if UNITY_2018_1_9
    Defined("UNITY_2018_1_9");
#endif
#if UNITY_2018_1_10
    Defined("UNITY_2018_1_10");
#endif
#if UNITY_2018_1_11
    Defined("UNITY_2018_1_11");
#endif
#if UNITY_2018_2
    Defined("UNITY_2018_2");
#endif
#if UNITY_2018_2_0
    Defined("UNITY_2018_2_0");
#endif
#if UNITY_2018_2_1
    Defined("UNITY_2018_2_1");
#endif
#if UNITY_2018_2_2
    Defined("UNITY_2018_2_2");
#endif
#if UNITY_2018_2_3
    Defined("UNITY_2018_2_3");
#endif
#if UNITY_2018_2_4
    Defined("UNITY_2018_2_4");
#endif
#if UNITY_2018_2_5
    Defined("UNITY_2018_2_5");
#endif
#if UNITY_2018_2_6
    Defined("UNITY_2018_2_6");
#endif
#if UNITY_2018_2_7
    Defined("UNITY_2018_2_7");
#endif
#if UNITY_2018_2_8
    Defined("UNITY_2018_2_8");
#endif
#if UNITY_2018_2_9
    Defined("UNITY_2018_2_9");
#endif
#if UNITY_2018_2_10
    Defined("UNITY_2018_2_10");
#endif
#if UNITY_2018_2_11
    Defined("UNITY_2018_2_11");
#endif
#if UNITY_2018_3
    Defined("UNITY_2018_3");
#endif
#if UNITY_2018_3_0
    Defined("UNITY_2018_3_0");
#endif
#if UNITY_2018_3_1
    Defined("UNITY_2018_3_1");
#endif
#if UNITY_2018_3_2
    Defined("UNITY_2018_3_2");
#endif
#if UNITY_2018_3_3
    Defined("UNITY_2018_3_3");
#endif
#if UNITY_2018_3_4
    Defined("UNITY_2018_3_4");
#endif
#if UNITY_2018_3_5
    Defined("UNITY_2018_3_5");
#endif
#if UNITY_2018_3_6
    Defined("UNITY_2018_3_6");
#endif
#if UNITY_2018_3_7
    Defined("UNITY_2018_3_7");
#endif
#if UNITY_2018_3_8
    Defined("UNITY_2018_3_8");
#endif
#if UNITY_2018_3_9
    Defined("UNITY_2018_3_9");
#endif
#if UNITY_2018_3_10
    Defined("UNITY_2018_3_10");
#endif
#if UNITY_2018_3_11
    Defined("UNITY_2018_3_11");
#endif
#if UNITY_2018_4
    Defined("UNITY_2018_4");
#endif
#if UNITY_2018_4_0
    Defined("UNITY_2018_4_0");
#endif
#if UNITY_2018_4_1
    Defined("UNITY_2018_4_1");
#endif
#if UNITY_2018_4_2
    Defined("UNITY_2018_4_2");
#endif
#if UNITY_2018_4_3
    Defined("UNITY_2018_4_3");
#endif
#if UNITY_2018_4_4
    Defined("UNITY_2018_4_4");
#endif
#if UNITY_2018_4_5
    Defined("UNITY_2018_4_5");
#endif
#if UNITY_2018_4_6
    Defined("UNITY_2018_4_6");
#endif
#if UNITY_2018_4_7
    Defined("UNITY_2018_4_7");
#endif
#if UNITY_2018_4_8
    Defined("UNITY_2018_4_8");
#endif
#if UNITY_2018_4_9
    Defined("UNITY_2018_4_9");
#endif
#if UNITY_2018_4_10
    Defined("UNITY_2018_4_10");
#endif
#if UNITY_2018_4_11
    Defined("UNITY_2018_4_11");
#endif
#if UNITY_2018_5
    Defined("UNITY_2018_5");
#endif
#if UNITY_2018_5_0
    Defined("UNITY_2018_5_0");
#endif
#if UNITY_2018_5_1
    Defined("UNITY_2018_5_1");
#endif
#if UNITY_2018_5_2
    Defined("UNITY_2018_5_2");
#endif
#if UNITY_2018_5_3
    Defined("UNITY_2018_5_3");
#endif
#if UNITY_2018_5_4
    Defined("UNITY_2018_5_4");
#endif
#if UNITY_2018_5_5
    Defined("UNITY_2018_5_5");
#endif
#if UNITY_2018_5_6
    Defined("UNITY_2018_5_6");
#endif
#if UNITY_2018_5_7
    Defined("UNITY_2018_5_7");
#endif
#if UNITY_2018_5_8
    Defined("UNITY_2018_5_8");
#endif
#if UNITY_2018_5_9
    Defined("UNITY_2018_5_9");
#endif
#if UNITY_2018_5_10
    Defined("UNITY_2018_5_10");
#endif
#if UNITY_2018_5_11
    Defined("UNITY_2018_5_11");
#endif
#if UNITY_2018_6
    Defined("UNITY_2018_6");
#endif
#if UNITY_2018_6_0
    Defined("UNITY_2018_6_0");
#endif
#if UNITY_2018_6_1
    Defined("UNITY_2018_6_1");
#endif
#if UNITY_2018_6_2
    Defined("UNITY_2018_6_2");
#endif
#if UNITY_2018_6_3
    Defined("UNITY_2018_6_3");
#endif
#if UNITY_2018_6_4
    Defined("UNITY_2018_6_4");
#endif
#if UNITY_2018_6_5
    Defined("UNITY_2018_6_5");
#endif
#if UNITY_2018_6_6
    Defined("UNITY_2018_6_6");
#endif
#if UNITY_2018_6_7
    Defined("UNITY_2018_6_7");
#endif
#if UNITY_2018_6_8
    Defined("UNITY_2018_6_8");
#endif
#if UNITY_2018_6_9
    Defined("UNITY_2018_6_9");
#endif
#if UNITY_2018_6_10
    Defined("UNITY_2018_6_10");
#endif
#if UNITY_2018_6_11
    Defined("UNITY_2018_6_11");
#endif
#if UNITY_2018_7
    Defined("UNITY_2018_7");
#endif
#if UNITY_2018_7_0
    Defined("UNITY_2018_7_0");
#endif
#if UNITY_2018_7_1
    Defined("UNITY_2018_7_1");
#endif
#if UNITY_2018_7_2
    Defined("UNITY_2018_7_2");
#endif
#if UNITY_2018_7_3
    Defined("UNITY_2018_7_3");
#endif
#if UNITY_2018_7_4
    Defined("UNITY_2018_7_4");
#endif
#if UNITY_2018_7_5
    Defined("UNITY_2018_7_5");
#endif
#if UNITY_2018_7_6
    Defined("UNITY_2018_7_6");
#endif
#if UNITY_2018_7_7
    Defined("UNITY_2018_7_7");
#endif
#if UNITY_2018_7_8
    Defined("UNITY_2018_7_8");
#endif
#if UNITY_2018_7_9
    Defined("UNITY_2018_7_9");
#endif
#if UNITY_2018_7_10
    Defined("UNITY_2018_7_10");
#endif
#if UNITY_2018_7_11
    Defined("UNITY_2018_7_11");
#endif
#if UNITY_2018_8
    Defined("UNITY_2018_8");
#endif
#if UNITY_2018_8_0
    Defined("UNITY_2018_8_0");
#endif
#if UNITY_2018_8_1
    Defined("UNITY_2018_8_1");
#endif
#if UNITY_2018_8_2
    Defined("UNITY_2018_8_2");
#endif
#if UNITY_2018_8_3
    Defined("UNITY_2018_8_3");
#endif
#if UNITY_2018_8_4
    Defined("UNITY_2018_8_4");
#endif
#if UNITY_2018_8_5
    Defined("UNITY_2018_8_5");
#endif
#if UNITY_2018_8_6
    Defined("UNITY_2018_8_6");
#endif
#if UNITY_2018_8_7
    Defined("UNITY_2018_8_7");
#endif
#if UNITY_2018_8_8
    Defined("UNITY_2018_8_8");
#endif
#if UNITY_2018_8_9
    Defined("UNITY_2018_8_9");
#endif
#if UNITY_2018_8_10
    Defined("UNITY_2018_8_10");
#endif
#if UNITY_2018_8_11
    Defined("UNITY_2018_8_11");
#endif
#if UNITY_2018_9
    Defined("UNITY_2018_9");
#endif
#if UNITY_2018_9_0
    Defined("UNITY_2018_9_0");
#endif
#if UNITY_2018_9_1
    Defined("UNITY_2018_9_1");
#endif
#if UNITY_2018_9_2
    Defined("UNITY_2018_9_2");
#endif
#if UNITY_2018_9_3
    Defined("UNITY_2018_9_3");
#endif
#if UNITY_2018_9_4
    Defined("UNITY_2018_9_4");
#endif
#if UNITY_2018_9_5
    Defined("UNITY_2018_9_5");
#endif
#if UNITY_2018_9_6
    Defined("UNITY_2018_9_6");
#endif
#if UNITY_2018_9_7
    Defined("UNITY_2018_9_7");
#endif
#if UNITY_2018_9_8
    Defined("UNITY_2018_9_8");
#endif
#if UNITY_2018_9_9
    Defined("UNITY_2018_9_9");
#endif
#if UNITY_2018_9_10
    Defined("UNITY_2018_9_10");
#endif
#if UNITY_2018_9_11
    Defined("UNITY_2018_9_11");
#endif
#if UNITY_2018_10
    Defined("UNITY_2018_10");
#endif
#if UNITY_2018_10_0
    Defined("UNITY_2018_10_0");
#endif
#if UNITY_2018_10_1
    Defined("UNITY_2018_10_1");
#endif
#if UNITY_2018_10_2
    Defined("UNITY_2018_10_2");
#endif
#if UNITY_2018_10_3
    Defined("UNITY_2018_10_3");
#endif
#if UNITY_2018_10_4
    Defined("UNITY_2018_10_4");
#endif
#if UNITY_2018_10_5
    Defined("UNITY_2018_10_5");
#endif
#if UNITY_2018_10_6
    Defined("UNITY_2018_10_6");
#endif
#if UNITY_2018_10_7
    Defined("UNITY_2018_10_7");
#endif
#if UNITY_2018_10_8
    Defined("UNITY_2018_10_8");
#endif
#if UNITY_2018_10_9
    Defined("UNITY_2018_10_9");
#endif
#if UNITY_2018_10_10
    Defined("UNITY_2018_10_10");
#endif
#if UNITY_2018_10_11
    Defined("UNITY_2018_10_11");
#endif
#if UNITY_2018_11
    Defined("UNITY_2018_11");
#endif
#if UNITY_2018_11_0
    Defined("UNITY_2018_11_0");
#endif
#if UNITY_2018_11_1
    Defined("UNITY_2018_11_1");
#endif
#if UNITY_2018_11_2
    Defined("UNITY_2018_11_2");
#endif
#if UNITY_2018_11_3
    Defined("UNITY_2018_11_3");
#endif
#if UNITY_2018_11_4
    Defined("UNITY_2018_11_4");
#endif
#if UNITY_2018_11_5
    Defined("UNITY_2018_11_5");
#endif
#if UNITY_2018_11_6
    Defined("UNITY_2018_11_6");
#endif
#if UNITY_2018_11_7
    Defined("UNITY_2018_11_7");
#endif
#if UNITY_2018_11_8
    Defined("UNITY_2018_11_8");
#endif
#if UNITY_2018_11_9
    Defined("UNITY_2018_11_9");
#endif
#if UNITY_2018_11_10
    Defined("UNITY_2018_11_10");
#endif
#if UNITY_2018_11_11
    Defined("UNITY_2018_11_11");
#endif
#if UNITY_2019
    Defined("UNITY_2019");
#endif
#if UNITY_2019_0
    Defined("UNITY_2019_0");
#endif
#if UNITY_2019_0_0
    Defined("UNITY_2019_0_0");
#endif
#if UNITY_2019_0_1
    Defined("UNITY_2019_0_1");
#endif
#if UNITY_2019_0_2
    Defined("UNITY_2019_0_2");
#endif
#if UNITY_2019_0_3
    Defined("UNITY_2019_0_3");
#endif
#if UNITY_2019_0_4
    Defined("UNITY_2019_0_4");
#endif
#if UNITY_2019_0_5
    Defined("UNITY_2019_0_5");
#endif
#if UNITY_2019_0_6
    Defined("UNITY_2019_0_6");
#endif
#if UNITY_2019_0_7
    Defined("UNITY_2019_0_7");
#endif
#if UNITY_2019_0_8
    Defined("UNITY_2019_0_8");
#endif
#if UNITY_2019_0_9
    Defined("UNITY_2019_0_9");
#endif
#if UNITY_2019_0_10
    Defined("UNITY_2019_0_10");
#endif
#if UNITY_2019_0_11
    Defined("UNITY_2019_0_11");
#endif
#if UNITY_2019_1
    Defined("UNITY_2019_1");
#endif
#if UNITY_2019_1_0
    Defined("UNITY_2019_1_0");
#endif
#if UNITY_2019_1_1
    Defined("UNITY_2019_1_1");
#endif
#if UNITY_2019_1_2
    Defined("UNITY_2019_1_2");
#endif
#if UNITY_2019_1_3
    Defined("UNITY_2019_1_3");
#endif
#if UNITY_2019_1_4
    Defined("UNITY_2019_1_4");
#endif
#if UNITY_2019_1_5
    Defined("UNITY_2019_1_5");
#endif
#if UNITY_2019_1_6
    Defined("UNITY_2019_1_6");
#endif
#if UNITY_2019_1_7
    Defined("UNITY_2019_1_7");
#endif
#if UNITY_2019_1_8
    Defined("UNITY_2019_1_8");
#endif
#if UNITY_2019_1_9
    Defined("UNITY_2019_1_9");
#endif
#if UNITY_2019_1_10
    Defined("UNITY_2019_1_10");
#endif
#if UNITY_2019_1_11
    Defined("UNITY_2019_1_11");
#endif
#if UNITY_2019_2
    Defined("UNITY_2019_2");
#endif
#if UNITY_2019_2_0
    Defined("UNITY_2019_2_0");
#endif
#if UNITY_2019_2_1
    Defined("UNITY_2019_2_1");
#endif
#if UNITY_2019_2_2
    Defined("UNITY_2019_2_2");
#endif
#if UNITY_2019_2_3
    Defined("UNITY_2019_2_3");
#endif
#if UNITY_2019_2_4
    Defined("UNITY_2019_2_4");
#endif
#if UNITY_2019_2_5
    Defined("UNITY_2019_2_5");
#endif
#if UNITY_2019_2_6
    Defined("UNITY_2019_2_6");
#endif
#if UNITY_2019_2_7
    Defined("UNITY_2019_2_7");
#endif
#if UNITY_2019_2_8
    Defined("UNITY_2019_2_8");
#endif
#if UNITY_2019_2_9
    Defined("UNITY_2019_2_9");
#endif
#if UNITY_2019_2_10
    Defined("UNITY_2019_2_10");
#endif
#if UNITY_2019_2_11
    Defined("UNITY_2019_2_11");
#endif
#if UNITY_2019_3
    Defined("UNITY_2019_3");
#endif
#if UNITY_2019_3_0
    Defined("UNITY_2019_3_0");
#endif
#if UNITY_2019_3_1
    Defined("UNITY_2019_3_1");
#endif
#if UNITY_2019_3_2
    Defined("UNITY_2019_3_2");
#endif
#if UNITY_2019_3_3
    Defined("UNITY_2019_3_3");
#endif
#if UNITY_2019_3_4
    Defined("UNITY_2019_3_4");
#endif
#if UNITY_2019_3_5
    Defined("UNITY_2019_3_5");
#endif
#if UNITY_2019_3_6
    Defined("UNITY_2019_3_6");
#endif
#if UNITY_2019_3_7
    Defined("UNITY_2019_3_7");
#endif
#if UNITY_2019_3_8
    Defined("UNITY_2019_3_8");
#endif
#if UNITY_2019_3_9
    Defined("UNITY_2019_3_9");
#endif
#if UNITY_2019_3_10
    Defined("UNITY_2019_3_10");
#endif
#if UNITY_2019_3_11
    Defined("UNITY_2019_3_11");
#endif
#if UNITY_2019_4
    Defined("UNITY_2019_4");
#endif
#if UNITY_2019_4_0
    Defined("UNITY_2019_4_0");
#endif
#if UNITY_2019_4_1
    Defined("UNITY_2019_4_1");
#endif
#if UNITY_2019_4_2
    Defined("UNITY_2019_4_2");
#endif
#if UNITY_2019_4_3
    Defined("UNITY_2019_4_3");
#endif
#if UNITY_2019_4_4
    Defined("UNITY_2019_4_4");
#endif
#if UNITY_2019_4_5
    Defined("UNITY_2019_4_5");
#endif
#if UNITY_2019_4_6
    Defined("UNITY_2019_4_6");
#endif
#if UNITY_2019_4_7
    Defined("UNITY_2019_4_7");
#endif
#if UNITY_2019_4_8
    Defined("UNITY_2019_4_8");
#endif
#if UNITY_2019_4_9
    Defined("UNITY_2019_4_9");
#endif
#if UNITY_2019_4_10
    Defined("UNITY_2019_4_10");
#endif
#if UNITY_2019_4_11
    Defined("UNITY_2019_4_11");
#endif
#if UNITY_2019_5
    Defined("UNITY_2019_5");
#endif
#if UNITY_2019_5_0
    Defined("UNITY_2019_5_0");
#endif
#if UNITY_2019_5_1
    Defined("UNITY_2019_5_1");
#endif
#if UNITY_2019_5_2
    Defined("UNITY_2019_5_2");
#endif
#if UNITY_2019_5_3
    Defined("UNITY_2019_5_3");
#endif
#if UNITY_2019_5_4
    Defined("UNITY_2019_5_4");
#endif
#if UNITY_2019_5_5
    Defined("UNITY_2019_5_5");
#endif
#if UNITY_2019_5_6
    Defined("UNITY_2019_5_6");
#endif
#if UNITY_2019_5_7
    Defined("UNITY_2019_5_7");
#endif
#if UNITY_2019_5_8
    Defined("UNITY_2019_5_8");
#endif
#if UNITY_2019_5_9
    Defined("UNITY_2019_5_9");
#endif
#if UNITY_2019_5_10
    Defined("UNITY_2019_5_10");
#endif
#if UNITY_2019_5_11
    Defined("UNITY_2019_5_11");
#endif
#if UNITY_2019_6
    Defined("UNITY_2019_6");
#endif
#if UNITY_2019_6_0
    Defined("UNITY_2019_6_0");
#endif
#if UNITY_2019_6_1
    Defined("UNITY_2019_6_1");
#endif
#if UNITY_2019_6_2
    Defined("UNITY_2019_6_2");
#endif
#if UNITY_2019_6_3
    Defined("UNITY_2019_6_3");
#endif
#if UNITY_2019_6_4
    Defined("UNITY_2019_6_4");
#endif
#if UNITY_2019_6_5
    Defined("UNITY_2019_6_5");
#endif
#if UNITY_2019_6_6
    Defined("UNITY_2019_6_6");
#endif
#if UNITY_2019_6_7
    Defined("UNITY_2019_6_7");
#endif
#if UNITY_2019_6_8
    Defined("UNITY_2019_6_8");
#endif
#if UNITY_2019_6_9
    Defined("UNITY_2019_6_9");
#endif
#if UNITY_2019_6_10
    Defined("UNITY_2019_6_10");
#endif
#if UNITY_2019_6_11
    Defined("UNITY_2019_6_11");
#endif
#if UNITY_2019_7
    Defined("UNITY_2019_7");
#endif
#if UNITY_2019_7_0
    Defined("UNITY_2019_7_0");
#endif
#if UNITY_2019_7_1
    Defined("UNITY_2019_7_1");
#endif
#if UNITY_2019_7_2
    Defined("UNITY_2019_7_2");
#endif
#if UNITY_2019_7_3
    Defined("UNITY_2019_7_3");
#endif
#if UNITY_2019_7_4
    Defined("UNITY_2019_7_4");
#endif
#if UNITY_2019_7_5
    Defined("UNITY_2019_7_5");
#endif
#if UNITY_2019_7_6
    Defined("UNITY_2019_7_6");
#endif
#if UNITY_2019_7_7
    Defined("UNITY_2019_7_7");
#endif
#if UNITY_2019_7_8
    Defined("UNITY_2019_7_8");
#endif
#if UNITY_2019_7_9
    Defined("UNITY_2019_7_9");
#endif
#if UNITY_2019_7_10
    Defined("UNITY_2019_7_10");
#endif
#if UNITY_2019_7_11
    Defined("UNITY_2019_7_11");
#endif
#if UNITY_2019_8
    Defined("UNITY_2019_8");
#endif
#if UNITY_2019_8_0
    Defined("UNITY_2019_8_0");
#endif
#if UNITY_2019_8_1
    Defined("UNITY_2019_8_1");
#endif
#if UNITY_2019_8_2
    Defined("UNITY_2019_8_2");
#endif
#if UNITY_2019_8_3
    Defined("UNITY_2019_8_3");
#endif
#if UNITY_2019_8_4
    Defined("UNITY_2019_8_4");
#endif
#if UNITY_2019_8_5
    Defined("UNITY_2019_8_5");
#endif
#if UNITY_2019_8_6
    Defined("UNITY_2019_8_6");
#endif
#if UNITY_2019_8_7
    Defined("UNITY_2019_8_7");
#endif
#if UNITY_2019_8_8
    Defined("UNITY_2019_8_8");
#endif
#if UNITY_2019_8_9
    Defined("UNITY_2019_8_9");
#endif
#if UNITY_2019_8_10
    Defined("UNITY_2019_8_10");
#endif
#if UNITY_2019_8_11
    Defined("UNITY_2019_8_11");
#endif
#if UNITY_2019_9
    Defined("UNITY_2019_9");
#endif
#if UNITY_2019_9_0
    Defined("UNITY_2019_9_0");
#endif
#if UNITY_2019_9_1
    Defined("UNITY_2019_9_1");
#endif
#if UNITY_2019_9_2
    Defined("UNITY_2019_9_2");
#endif
#if UNITY_2019_9_3
    Defined("UNITY_2019_9_3");
#endif
#if UNITY_2019_9_4
    Defined("UNITY_2019_9_4");
#endif
#if UNITY_2019_9_5
    Defined("UNITY_2019_9_5");
#endif
#if UNITY_2019_9_6
    Defined("UNITY_2019_9_6");
#endif
#if UNITY_2019_9_7
    Defined("UNITY_2019_9_7");
#endif
#if UNITY_2019_9_8
    Defined("UNITY_2019_9_8");
#endif
#if UNITY_2019_9_9
    Defined("UNITY_2019_9_9");
#endif
#if UNITY_2019_9_10
    Defined("UNITY_2019_9_10");
#endif
#if UNITY_2019_9_11
    Defined("UNITY_2019_9_11");
#endif
#if UNITY_2019_10
    Defined("UNITY_2019_10");
#endif
#if UNITY_2019_10_0
    Defined("UNITY_2019_10_0");
#endif
#if UNITY_2019_10_1
    Defined("UNITY_2019_10_1");
#endif
#if UNITY_2019_10_2
    Defined("UNITY_2019_10_2");
#endif
#if UNITY_2019_10_3
    Defined("UNITY_2019_10_3");
#endif
#if UNITY_2019_10_4
    Defined("UNITY_2019_10_4");
#endif
#if UNITY_2019_10_5
    Defined("UNITY_2019_10_5");
#endif
#if UNITY_2019_10_6
    Defined("UNITY_2019_10_6");
#endif
#if UNITY_2019_10_7
    Defined("UNITY_2019_10_7");
#endif
#if UNITY_2019_10_8
    Defined("UNITY_2019_10_8");
#endif
#if UNITY_2019_10_9
    Defined("UNITY_2019_10_9");
#endif
#if UNITY_2019_10_10
    Defined("UNITY_2019_10_10");
#endif
#if UNITY_2019_10_11
    Defined("UNITY_2019_10_11");
#endif
#if UNITY_2019_11
    Defined("UNITY_2019_11");
#endif
#if UNITY_2019_11_0
    Defined("UNITY_2019_11_0");
#endif
#if UNITY_2019_11_1
    Defined("UNITY_2019_11_1");
#endif
#if UNITY_2019_11_2
    Defined("UNITY_2019_11_2");
#endif
#if UNITY_2019_11_3
    Defined("UNITY_2019_11_3");
#endif
#if UNITY_2019_11_4
    Defined("UNITY_2019_11_4");
#endif
#if UNITY_2019_11_5
    Defined("UNITY_2019_11_5");
#endif
#if UNITY_2019_11_6
    Defined("UNITY_2019_11_6");
#endif
#if UNITY_2019_11_7
    Defined("UNITY_2019_11_7");
#endif
#if UNITY_2019_11_8
    Defined("UNITY_2019_11_8");
#endif
#if UNITY_2019_11_9
    Defined("UNITY_2019_11_9");
#endif
#if UNITY_2019_11_10
    Defined("UNITY_2019_11_10");
#endif
#if UNITY_2019_11_11
    Defined("UNITY_2019_11_11");
#endif
  }

  public virtual void Defined(string define) {
    Debug.Log(define + " defined.");
  }
}